#TODO: homonyme extra flaggen/extra dictionary
#TODO: a2 & b1 listen
a1 = ['ab', 'aber', 'abfahren', 'Abfahrt', 'abfliegen', 'Abflug', 'abgeben', 'abholen', 'Absender', 'Achtung',
      'Adresse', 'all', 'allein',
      'also', 'alt', 'Alter', 'an', 'an sein', 'anbieten', 'ander', 'Anfang', 'anfangen', 'Angebot', 'anklicken',
      'ankommen', 'ankreuzen',
      'Ankunft', 'anmachen', 'Anmeldung', 'Anruf', 'Anrufbeantworter', 'anrufen', 'Ansage', 'Anschluss', 'Antwort',
      'antworten', 'Anzeige',
      'Apartment', 'Apfel', 'Appetit', 'Arbeit', 'arbeiten', 'arbeitslos', 'Arbeitsplatz', 'Arm', 'Arzt', 'auch', 'auf',
      'auf sein', 'Aufgabe',
      'aufhören', 'aufstehen', 'Aufzug', 'Auge', 'aus', 'Ausflug', 'ausfüllen', 'Ausgang', 'Auskunft', 'Ausland',
      'Ausländer', 'ausländisch',
      'ausmachen', 'Aussage', 'aussehen', 'aussteigen', 'Ausweis', 'Auto', 'Autobahn', 'Automat', 'automatisch', 'Baby',
      'Bäckerei', 'Bad', 'baden', 'Bahn', 'Bahnhof', 'Bahnsteig', 'bald', 'Balkon', 'Banane', 'Bank', 'bar', 'Bauch',
      'Baum', 'Beamte', 'bedeuten', 'beginnen', 'bei', 'beide', 'Bein', 'Beispiel', 'bekannt', 'bekommen', 'benutzen',
      'Beruf', 'besetzt', 'besichtigen', 'besser', 'best', 'bestellen', 'besuchen', 'Bett', 'bezahlen', 'Bier', 'Bild',
      'billig', 'Birne', 'bis', 'bisschen', 'bitte', 'Bitte', 'bitten', 'bitter', 'bleiben', 'Bleistift', 'Blick',
      'Blume', 'Bogen', 'böse', 'brauchen', 'breit', 'Brief', 'Briefmarke', 'bringen', 'Brot', 'Brötchen', 'Bruder',
      'Buchr', 'Buchstabe', 'buchstabieren', 'Buse', 'Butter', 'ca.', 'Café', 'CD', 'Chef', 'circa', 'Computer', 'da',
      'Dame', 'daneben', 'Dank', 'danke', 'danken', 'dann', 'das', 'das', 'Datum', 'dauern', 'dein', 'denn', 'der',
      'der/Bekannte', 'dich', 'die', 'dies', 'dir', 'Disco', 'Doktor', 'Doppelzimmer', 'Dorf', 'dortherhin', 'draußen',
      'drucken', 'drücken', 'Drucker', 'durch', 'Durchsage', 'dürfen', 'Durst', 'Dusche', 'Ecke', 'Ehefrau', 'Ehemann',
      'Ei', 'eilig', 'ein', 'einfach', 'Eingang', 'einkaufen', 'einladen', 'Einladung', 'einmal', 'einsteigen',
      'Eintritt', 'Einzelzimmer', 'Eltern', 'EMail', 'Empfänger', 'empfehlen', 'Ende', 'enden', 'entschuldigen',
      'Entschuldigung', 'er', 'Ergebnise', 'erklären', 'erlauben', 'Erwachsene', 'erzählen', 'es', 'essen', 'Essen',
      'euer', 'fahren', 'Fahrer', 'Fahrkarte', 'Fahrradr', 'falsch', 'Familie', 'Familienname', 'Familienstand',
      'Farbe', 'Fax', 'fehlen', 'Fehler', 'Feier', 'feiern', 'fernsehen', 'fertig', 'Feuer', 'Fieber', 'Film', 'finden',
      'Firma', 'Fisch', 'Flasche', 'Fleisch', 'fliegen', 'Flughafen', 'Flugzeug', 'Formular', 'Foto', 'Frage', 'fragen',
      'Frau', 'frei', 'Freizeit', 'fremd', 'Freund', 'früher', 'Frühstück', 'frühstücken', 'Führung', 'für', 'Fuß',
      'Fußball', 'Garten', 'Gast', 'geben', 'geboren', 'Geburtsjahr', 'Geburtsort', 'Geburtstag', 'gefallen', 'gegen',
      'gehen', 'gehören', 'Geld', 'Gemüse', 'geöffnet', 'Gepäck', 'gerade', 'geradeaus', 'gerne', 'Geschäft',
      'Geschenk', 'geschlossen', 'Geschwister', 'Gespräch', 'gestern', 'gestorben', 'Getränk', 'Gewicht', 'gewinnen',
      'Glasr', 'glauben', 'gleich', 'Gleis', 'Glück', 'glücklich', 'Glückwunsch', 'Grad Celsius', 'gratulieren',
      'grillen', 'groß', 'Größe', 'Großeltern', 'Großmutter', 'Großvater', 'Gruppe', 'Gruß', 'gültig', 'günstig', 'gut',
      'Haar', 'haben', 'Hähnchen', 'Halbpension', 'Halle', 'hallo', 'halten', 'Haltestelle', 'Hand', 'Handy',
      'Hausaufgabe', 'Hausfrau/', 'Hausmann', 'Hausr', 'Heimat', 'heiraten', 'heißen', 'helfen', 'hell', 'Herd', 'Herr',
      'herzlich', 'heute', 'hier', 'Hilfe', 'hinten', 'Hobby', 'hoch', 'Hochzeit', 'holen', 'hören', 'Hotel', 'Hund',
      'Hunger', 'ich', 'ihr/ihm/ihn', 'immer', 'in', 'Information', 'international', 'Internet', 'ja', 'Jacke', 'jed',
      'jetzt', 'Job', 'Jugendliche', 'jung', 'Junge', 'Kaffee', 'kaputt', 'Karte', 'Kartoffel', 'Kasse', 'kaufen',
      'kein', 'kennen', 'kennenlernen', 'Kind', 'Kindergarten', 'Kino', 'Kiosk', 'klar', 'Klasse', 'Kleidung', 'klein',
      'kochen', 'Koffer', 'Kollege', 'kommen', 'können', 'Konto', 'Kopf', 'kosten', 'krank', 'KreditKarte', 'kriegen',
      'Küche', 'Kuchen', 'Kugelschreiber', 'Kühlschrank', 'kulturell', 'Kunde', 'Kurs', 'kurz', 'lachen', 'Laden',
      'Landr', 'lang', 'lange', 'langsam', 'laufen', 'laut', 'leben', 'Leben', 'Lebensmittel', 'ledig', 'legen',
      'Lehrer', 'leicht', 'leider', 'leise', 'lernen', 'lesen', 'letzt', 'Leute', 'Licht', 'lieb', 'lieben', 'lieber',
      'Lieblings', 'Lied', 'liegen', 'links', 'Lkw', 'Lokal', 'Lösung', 'lustig', 'machen', 'Mädchen', 'man',
      'männlich', 'Mannr', 'Maschine', 'Meer', 'mehr', 'mein', 'meist', 'Mensch', 'Miete', 'mieten', 'Milch', 'mit',
      'mitbringen', 'mitkommen', 'mitmachen', 'mitnehmen', 'Mitte', 'Möbel', 'möchten', 'mögen', 'möglich', 'Moment',
      'morgen', 'müde', 'Mund', 'müssen', 'Mutter', 'nach', 'nächst', 'Name', 'nehmen', 'nein', 'neu', 'nicht',
      'nichts', 'nie', 'noch', 'normal', 'Nummer', 'nur', 'oben', 'Obst', 'oder', 'öffnen', 'oft', 'ohne', 'Öl', 'Oma',
      'Opa', 'Ordnung', 'Ort', 'Papier', 'Papiere', 'Partner', 'Partnerinen', 'Party', 'Pass', 'Pause', 'Plan', 'Platz',
      'Polizei', 'Pommes frites', 'Post', 'Postleitzahl', 'Praktikum', 'Praxis', 'Preis', 'Problem', 'Prospekt',
      'Prüfung', 'pünktlich', 'Rad fahren', 'rauchen', 'Raum', 'Rechnung', 'rechts', 'Regen', 'regnen', 'Reis', 'Reise',
      'Reisebüro', 'Reiseführer', 'reisen', 'Reparatur', 'reparieren', 'Restaurant', 'Rezeption', 'richtig', 'riechen',
      'ruhig', 'Saft', 'sagen', 'Salat', 'Salz', 'Satz', 'SBahn', 'Schalter', 'scheinen', 'schicken', 'Schild',
      'Schinken', 'schlafen', 'schlecht', 'schließen', 'Schluss', 'Schlüssel', 'schmecken', 'schnell', 'schon', 'schön',
      'Schrank', 'schreiben', 'Schuh', 'Schule', 'Schüler', 'schwer', 'Schwester', 'Schwimmbad', 'schwimmen', 'See',
      'sehen', 'Sehenswürdigkeit', 'sehr', 'sein', 'seit', 'selbstständig', 'sich', 'anmelden', 'anziehen', 'ausziehen',
      'duschen', 'freuen', 'kümmern', 'treffen', 'vorstellen', 'waschen', 'sie', 'Sie', 'sitzen', 'so', 'Sofa',
      'sofort', 'Sohn', 'sollen', 'Sonne', 'spät', 'später', 'Speisekarte', 'spielen', 'Sport', 'Sprache', 'sprechen',
      'Stadt', 'stehen', 'Stelle', 'stellen', 'Stock', 'Straße', 'Straßenbahn', 'Student', 'studieren', 'Studium',
      'Stunde', 'suchen', 'tanzen', 'Tasche', 'Taxi', 'Tee', 'Teil', 'Telefon', 'telefonieren', 'Termin', 'Test',
      'teuer', 'Text', 'Thema', 'Ticket', 'Tisch', 'Tochter', 'Toilette', 'Tomate', 'tot', 'Treppe', 'trinken',
      'tschüss', 'tun', 'über', 'übernachten', 'überweisen', 'Uhr', 'um', 'umziehen', 'und', 'unser', 'unten', 'unter',
      'Unterricht', 'unterschreiben', 'Unterschrift', 'Urlaub', 'Vater', 'verboten', 'verdienen', 'Verein',
      'verheiratet', 'verkaufen', 'Verkäufer', 'vermieten', 'Vermieter', 'verstehen', 'Verwandte', 'vielleicht', 'von',
      'vor', 'Vorname', 'Vorsicht', 'Vorwahl', 'wandern', 'wann', 'warten', 'warum', 'was', 'was für ein', 'Wasser',
      'weg sein', 'weh tun', 'weiblich', 'Wein', 'weit', 'weiter', 'welch', 'Welt', 'wenig', 'wer', 'werden', 'Wetter',
      'wichtig', 'wie', 'wie viel', 'wiederholen', 'Wiederhören', 'Wiedersehen', 'willkommen', 'Wind', 'wir', 'wissen',
      'wo', 'woher', 'wohin', 'wohnen', 'Wohnung', 'Wort', 'wunderbar', 'z. B.', 'zahlen', 'Zeit', 'Zeitung',
      'Zigarette', 'Zimmer', 'Zoll', 'zu', 'zufrieden', 'Zug', 'zum Beispiel', 'zurück', 'zurzeit', 'zusammen',
      'zwischen']

a2 = ['miau', 'schwierig', 'Wort']
